## Numpy 
* Numpy bir python kütüphanesidir. Bu kütüphane matematiksel işlemler yaparak veri işlemleri gerçek-
leştirir.


In [1]:
# numpy kütüphanesi np kısaltma adıyla aşağıdaki gibi eklenir:
import numpy as np

In [2]:
# Dizi (array) oluşturma:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [3]:
# Dizinin veri tipini öğrenme: Yukarıdaki dizinin tipi numpy veri tiplerinden ndarray tipindedir. Python’da
# olduğu gibi numpy kütüphanesinin de kendine özgü veri tipleri vardır. ndarray bunlardan biridir.
type(array)

numpy.ndarray

In [4]:
# Dizi içindeki verilerin tipini öğrenme: Yukarıdaki dizinin içindeki veriler int32 veri tipindedir.
array.dtype

dtype('int64')

In [5]:
# Numpy içindeki verilerin tipi en geniş anlamda tanımlanır: Örneğin dizinin içinde hem tam sayı hem
# de float türü sayı varsa bu durumda dtype değeri float olarak belirlenir. Çünkü float veri türü tam sayı-
# ları da kapsar. Kısacası NumPy dizileri, bellek verimliliği ve performans nedeniyle homojen veri tipleri
# gerektirir bu nedenle bir dizi için sadece tek bir veri tipi tanımlanır. Örnek:
array = np.array( [1, 1.5, 2, 2.5, 3, 3.5, 4] )
array.dtype

dtype('float64')

In [7]:
# Dizi içindeki verilerin tipini belirleme: Dizi içindeki verilerin tipini aşağıdaki gibi önceden belirleyebiliriz.
array = np.array( [1 ,2, 3, 4, 5, 6] , dtype=float)
array

array([1., 2., 3., 4., 5., 6.])

In [8]:
# İki boyutlu bir dizi oluşturma:
array = np.array([ [1, 2, 3] , [4, 5, 6] ])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# Dizilerin kaç boyutlu olduğunu öğrenme: 
array.ndim

2

In [11]:
# Dizilerin satır ve sütun sayısını öğrenme:
array.shape

(2, 3)

In [12]:
array = np.array( [1, 2, 3, 4, 5, 6] )
# yukarıdaki diziyi 2 adet satır ve 3 adet sütuna dönüştürüyoruz.
array.reshape(2, 3)
# Ek bilgi: shape oluştururken satır ve sütun sayılarının çarpımı dizi eleman sayısına eşit olmalıdır.

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Otomatik sayı dizisi oluşturma:
# 0'dan başlayarak 30'a kadar (30 dâhil değil) dizi oluşturma
array = np.arange(30)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
# Sabit aralıklı otomatik sayı dizisi oluşturma:
# 0'dan başlayarak 30'a kadar üçer sıra atlayarak dizi oluşturma
array = np.arange(0, 30, 3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [15]:
# Bir diziyi kopyalama: Yukarıdaki diziyi kopyalayalım
array_2 = array.copy()
array_2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [16]:
# Rastgele sayılardan oluşan bir dizi oluşturma:
# dört adet rastgele sayıdan oluşan tek boyutlu bir dizi oluşturma
array = np.random.random((4))
array

array([0.25635211, 0.01222023, 0.14400197, 0.94297554])

In [17]:
# Rastgele tamsayılardan oluşan tek boyutlu bir dizi oluşturma
array = np.random.randint(20, size=4)
array
# 20 değeri üretilecek sayıların 20'den küçük olmasını sağlar.
# size özelliği kaç adet sayı üretileceğini belirler

array([ 5, 16, 19, 12])

In [18]:
# 2 satırlı, 4 sütunlu rastgele sayılardan oluşan iki boyutlu bir dizi oluşturma
array = np.random.random( (2, 4) )
array

array([[0.49370114, 0.37436487, 0.25209878, 0.43086044],
       [0.84369718, 0.56258404, 0.91755791, 0.66437465]])

In [19]:
# 2 satırlı, 4 sütunlu rastgele tam sayılardan oluşan iki boyutlu bir dizi oluşturma
# 0 ve 10 arası tam sayı üretelim
array = np.random.randint(0, 10, size=(2, 4))
array

array([[3, 8, 9, 2],
       [3, 3, 3, 8]])

In [21]:
#Dizilerde indis verilerine ulaşma:
dizi = np.array([[1,2,3],[4,5,6]])
# İlgili dizinin ilk satırını döndürme
dizi[0]


array([1, 2, 3])

In [22]:
dizi[1]

array([4, 5, 6])

In [23]:
# Reshape bir dizinin şeklini değiştirmek demektir. Dizinin her boyutundaki elemanların sayısını aşa-
# ğıdaki gibi belirleyebiliriz.
array = np.arange(8)
array = array.reshape(4, 2)
array
# yukarıdaki kodlar çalıştırıldığında 4 satırlı ve 2 sütunlu aşağıdaki gibi bir dizi elde edilir.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
# Bu dizi referans alınarak aşağıdaki işlemler yapılabilir:
# dizinin ilk iki satırını döndürme
array[0 : 2]

array([[0, 1],
       [2, 3]])

In [29]:
# Dizinin ilk sütununu döndürme. Virgülün solu satırları, sağı ise sütunları belirler. Bu örnekte tüm
# satırlar seçilmiş ancak sadece sıfırıncı indisteki sütunlar seçilmiştir.
array[:,0]

array([0, 2, 4, 6])

In [30]:
# Dizinin üçüncü satırının ikinci değerini döndürme
array[2,1]

5

In [31]:
# 5 satır ve 3 sütundan ve sıfırlardan oluşan matris örmeği
array= np.zeros((5, 3))
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# 2 boyutlu 1’lerden oluşan matris örneği:
array = np.ones((4,3))
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
# Birim matris oluşturma örneği: x boyutlu bir birim matriste, köşeden çapraz olan değerler birlerden,
# diğer değerler ise sıfırlardan oluşur. Aşağıdaki örnekte x değeri 3 olarak verilmiştir.
array = np.eye(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# Matris birleştirme:
matris1 = np.array([[1, 2, 3] , [4, 5, 6]])
matris2 = np.array([[7, 8, 9] , [10, 11, 12]])
combine = np.concatenate([matris1, matris2])
combine

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
# Matris birleştirmede eğer ‘axis’ değeri kullanırsa matrisler yan yana diziliş gösterir. Yukarıdaki ko-
# dumuzu şu şekilde yazalım ve çıktımızı görelim:
combine = np.concatenate([matris1,matris2] , axis = 1)
combine

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [39]:
# Bir dizinin maximum değerini bulma:
combine.max()

12

In [40]:
# Bir dizinin minumum değerini bulma:
combine.min()

1

In [41]:
# Bir dizideki tüm değerlerin toplamını bulma:
combine.sum()

78

In [42]:
#Bir dizideki tüm satırların toplamını bulma:
combine.sum(axis=1)

array([30, 48])

In [43]:
# Bir dizideki tüm sütunların toplamını bulma:
# axis değeri 0 olursa sütunların toplamını alır
combine.sum(axis=0)

array([ 5,  7,  9, 17, 19, 21])

In [44]:
# Bir dizideki tüm değerlerin ortalamasını bulma:
combine.mean()

6.5

In [45]:
# Bir dizideki varyansı bulma:
# Varyans nedir?
# "Varyans" istatistiksel bir terimdir ve bir veri kümesindeki değerlerin ortalamadan ne kadar
# sapma gösterdiğini ölçer. Yani varyans, bir veri kümesindeki her bir verinin ortalamadan ne kadar uzak-
# laştığına bağlı olarak veri dağılımının ne kadar geniş olduğunu ölçer. Varyans, bir veri kümesindeki her
# bir verinin ortalamadan ne kadar farklı olduğunu ölçmek için kullanılan kareli sapma değerlerinin top-
# lamının n-1'e bölünmesi ile hesaplanır. Burada n, veri kümesindeki toplam örneklemlerin sayısını temsil
# eder. Varyansın kareköküne standart sapma denir ve varyansın ölçüm birimi ile aynı birimde ifade edi-
# lir. Daha düşük bir varyans değeri, veri kümesindeki örneklerin ortalamaya daha yakın olduğu anlamına
# gelirken, daha yüksek bir varyans değeri, örneklerin ortalamadan daha fazla uzaklaştığı anlamına gelir."""
combine.var()

11.916666666666666

In [46]:
# Standart sapma nedir?
# Standart sapma, bir veri kümesindeki değerlerin ortalamadan ne kadar sapma gösterdiğini öl-
# çen bir istatistik terimidir. Standart sapma, veri kümesindeki her bir örneğin ortalamadan ne kadar
# farklı olduğunu hesaplamak için kullanılır. Standart sapma, veri kümesindeki örneklemlerin her birinin
# ortalamadan farkının karelerinin toplamının, örneklemlerin sayısının bir eksiğiyle bölümünden hesap-
# lanır. Bu hesaplamayla, standart sapma, veri kümesindeki örneklerin ne kadar yayıldığını, ne kadar de-
# ğişken olduğunu ölçer. Standart sapma, varyansın karekökü olarak hesaplanabilir. Varyans, standart
# sapmanın karesidir ve standart sapma varyansın kareköküdür. Standart sapma, varyans gibi, veri kü-
# mesinin ölçüm birimi ile aynı birimde ifade edilir. Bir veri kümesindeki standart sapma daha yüksekse,
# veri kümesindeki örneklerin ortalamadan daha fazla sapma gösterdiği anlamına gelir ve veri kümesinin
# daha değişken olduğunu ifade eder. Standart sapma daha düşükse, veri kümesindeki örneklerin orta-
# lamaya daha yakın olduğu ve veri kümesinin daha homojen olduğu anlamına gelir.
combine.std()

3.452052529534663